language: java
jdk:
  - oraclejdk7
before_install:  
 - sudo apt-get update  
 - sudo apt-get install ruby
 - sudo apt-get install rubygems
 - sudo gem install bundler
services:
  - mongodb
script: ./travis_build.sh
cache:
  directories:
  - idea-IC