language: java
jdk:
  - oraclejdk8
before_install:
 - sudo apt-get update
 - sudo apt-get install ruby
 - sudo apt-get install rubygems-integration
 - sudo gem install bundler
 - ./travis_build.sh
services:
  - mongodb
script: ./travis_test.sh
