language: java
jdk:
  - oraclejdk8
before_install:
 - sudo apt-get update
 - sudo apt-get install ruby
 - sudo apt-get install rubygems-integration
 - sudo gem install bundler
 - ./WatchDogIntelliJPlugin/fetchidea.sh
services:
  - mongodb
script: mvn verify
