source 'https://rubygems.org'

ruby "2.4.1"

gem 'mongo'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'bson_ext'
gem 'geocoder'

github 'sinatra/sinatra' do
  gem 'rack-protection'
end

group :test do
  gem 'rspec', "~>3"
  gem 'rack-test'
  gem 'nyan-cat-formatter'
  gem 'codeclimate-test-reporter', '~> 0.4.7'
end

group :production do
  gem 'unicorn'
end
