source 'https://rubygems.org'

ruby "1.9.3"

gem 'mongo'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'bson_ext'
gem 'geocoder'

group :test do
  gem 'rspec', "~>2.9"
  gem 'nyan-cat-formatter'
  gem 'codeclimate-test-reporter', '~> 0.4.7'
end

group :production do
  gem 'unicorn'
end
