#! /bin/sh
# /etc/init.d/watchdog
#
#
#
### BEGIN INIT INFO
# Provides:          watchdog 
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      $named
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Watchdog server 
# Description:       Watchdog is high-performance and open source.
#                    High performance, scalability, and reasonable depth of
#                    functionality are the goals for the project.
#
### END INIT INFO


# Some things that run always
touch /var/lock/watchdog

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting watchdog server with supervise"
    sudo -u testroots bash --login supervise /home/testroots/watchdog/WatchDogServer
    ;;
  stop)
    echo "Stopping watchdog server"
    sudo -u testroots bash --login svc -d /home/testroots/watchdog/WatchDogServer
     ;;
  *)
    echo "Usage: /etc/init.d/watchdog {start|stop}"
    exit 1
    ;;
esac

exit 0
